{% set name = "numericalunits" %}
{% set version = "1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a0b69945dd65eacf6eef8c868bcd3298d7439f5882f507bb6060ec20c723e12

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pip

test:
  imports:
    - numericalunits
  commands:
    - pip check

about:
  home: https://github.com/sbyrnes321/numericalunits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'numericalunits: Units and dimensional analysis compatible with everything'

  description: |
    This package implements units and dimensional analysis in an 
    unconventional way that has the following unique advantages:
    Compatible with everything, Modular and non-intrusive, 
    Powerful tool for debugging, Zero storage overhead and 
    Zero calculation overhead
  doc_url: https://github.com/sbyrnes321/numericalunits
  dev_url: https://github.com/sbyrnes321/numericalunits

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
